---
- name: Include variables
  include_vars:
    file: ../../vars.yaml

- name: Add /etc/hosts information
  become: yes
  blockinfile:
    path: /etc/hosts
    marker: '#'
    block: |
      {{ item.ip }} {{ item.name }}
  loop:
    - { name: elk1, ip: "{{ elastic_ip }}" }
    - { name: elk2, ip: "{{ elastic_node01_ip }}" }
    - { name: elk4, ip: "{{ logstash_ip }}"}
    - { name: elk5, ip: "{{ kibana_ip }}" }
