---
- name: Include variables
  include_vars:
    file: ../../vars.yaml

- name: reload systemd config
  ansible.builtin.systemd:
    daemon_reload: yes


- name: enable service elasticsearch and ensure it is not masked
  ansible.builtin.systemd:
    name: elasticsearch
    enabled: yes
    masked: no

- name: ensure elasticsearch is running
  ansible.builtin.systemd: 
    state: started 
    name: elasticsearch

- name: Remove Elastic Config YAML
  file:
      path: "{{ elastic_yaml }}"
      state: absent

- name: Wait for 2 seconds to allow config to be deleted
  wait_for:
    timeout: 2

- name: Add Details To Elastic Config YAML
  blockinfile:
    path: "{{ elastic_yaml }}"
    create: yes
    marker: ''
    block: |
       cluster.name: {{ elastic_cluster_name }}
       node.name: {{ inventory_hostname }}
       network.host: 0.0.0.0
       http.port: {{ elastic_port }}
       node.master: false
       node.data: true
       node.ingest: false
       discovery.seed_hosts: [{{ elastic_discovery_seeds }}]
       cluster.initial_master_nodes: [{{ elastic_master_nodes }}]
       path.data: /var/lib/elasticsearch
       path.logs: /var/log/elasticsearch

- name: set elasticsearch permissions
  file:
    path: /usr/share/elasticsearch
    state: directory
    recurse: yes
    owner: elasticsearch
    group: elasticsearch

- name: Set min JVM Heap size.
  ansible.builtin.lineinfile:
    path: /etc/elasticsearch/jvm.options.d/heap_size
    create: yes
    regexp: "^-Xms"
    line: "-Xms{{ elasticsearch_jvm_xms }}"

- name: Set max JVM Heap size.
  ansible.builtin.lineinfile:
    path: /etc/elasticsearch/jvm.options.d/heap_size
    create: yes
    regexp: "^-Xmx"
    line: "-Xmx{{ elasticsearch_jvm_xmx }}"

- name: Restart ElasticSearch Service
  ansible.builtin.systemd: 
    name: elasticsearch
    state: restarted
