---
- name: Include variables
  include_vars:
    file: ../../vars.yaml

- name: Install rpm key
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  when: ansible_facts['distribution']=="Amazon"

- name: Install base rpm repository
  yum_repository:
    name: kibana-7.x
    description: Kibana repository for 7.x packages
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: true
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  when: ansible_facts['distribution']=="Amazon"

- name: Install Kibana Yum Package
  yum:
    name: kibana
    state: present
    update_cache: true
  when: ansible_facts['distribution']=="Amazon"

- name: reload systemd config
  ansible.builtin.systemd:
    daemon_reload: yes

- name: enable service kibana and ensure it is not masked
  ansible.builtin.systemd:
    name: kibana
    enabled: yes
    masked: no

- name: Create a certificate directory
  file:
    owner: kibana
    group: kibana
    recurse: yes
    mode: u=rwx,g+rx,o-rwx
    path: /etc/kibana/certs
    state: directory

- name: Copy the kibana certs from local to server
  copy: 
    src: "files/{{ kibana_dns }}"
    dest: "/etc/kibana/certs/"

- name: Copy CA to server
  copy: 
    src: "files/ca.crt"
    dest: "/etc/kibana/certs/ca.crt"

- name: set kibana permissions
  file:
    path: /usr/share/kibana
    state: directory
    recurse: yes
    owner: kibana
    group: kibana

- name: Backup default kibana config
  ansible.builtin.command: mv /etc/kibana/kibana.yml /etc/kibana/kibana.bkp.yml

- name: Add Details To Kibana Config YAML
  blockinfile:
    path: /etc/kibana/kibana.yml
    create: yes
    marker: ''
    block: |
      server.host: 0.0.0.0
      server.ssl.enabled: true
      server.ssl.key: /etc/kibana/certs/{{ kibana_dns }}/{{ kibana_dns }}.key
      server.ssl.certificate: /etc/kibana/certs/{{ kibana_dns }}/{{ kibana_dns }}.crt
      elasticsearch.hosts: ["https://{{ elastic_dns }}:9200", "https://{{ elastic_node01_dns }}:9200", "https://{{ elastic_node02_dns }}:9200"]
      elasticsearch.ssl.certificateAuthorities: [ "/etc/kibana/certs/ca.crt" ]
      elasticsearch.ssl.verificationMode: "full" 

- name: Restart Kibana Service
  ansible.builtin.systemd: 
    name: kibana
    state: restarted
